language: node_js
node_js:
  - 'node'
  - '6.9'

cache:
  directories:
    - node_modules

env:
  global:
    - CXX: g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services: mongodb

before_script: npm run build
